ExampleWebProject/Controllers/ContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExampleWebProject.Controllers
{
    public class ContentController : Controller
    {
        ContentManager cm = new ContentManager(new EfContentDal());
        // GET: Content
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ContentByHeading(int id) //basliklarin icerigi
        {
            var contentValues = cm.GetListByHeadingID(id);
            return View(contentValues);
        }

        public ActionResult GetAllContent(string p)
        {
            if (p == null)
            {
                var vls = cm.GetList();
                return View(vls.ToList());
            }
            else
            {
                var values = cm.GetList(p);
                return View(values);
            }
        }
    }
}

ExampleWebProject/Views/Content/ContentByHeading.cshtml
@using EntityLayer.Concrete
@model List<Content>

@{
    ViewBag.Title = "ContentByHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            @foreach (var item in Model)
                            {
                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MMM-yyyy"))</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Writer.WriterName @item.Writer.WriterSurname</a> </h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                            }
                            <!-- END timeline item -->
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

ExampleWebProject/Views/Content/GetAllContent.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "GetAllContent";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}



@using(Html.BeginForm("GetAllContent","Content",FormMethod.Post))
{
    <p>
        Ara: @Html.TextBox("p")
        <input type="submit" value="Ara"/>
    </p>
    

}

@foreach (var item in Model)
{
    
    <br/>
<div style="background-color: #B0C4DE; border: 3px solid #33475b; margin: 0px 60px 15px 5px; ">
    
    <p>@item.ContentValue</p>
</div>
}
<br/>