ExampleWebProject/Controllers/AuthorizationController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExampleWebProject.Controllers
{
    public class AuthorizationController : Controller
    {
        AdminManager adm = new AdminManager(new EfAdminDal()); 
        // GET: Authorization
        public ActionResult Index()
        {
            var adminvalues = adm.GetList();
            return View(adminvalues);
        }

        [HttpGet]
        public ActionResult AddAdmin()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddAdmin(Admin admin)
        {
            adm.AdminAdd(admin);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult EditAdmin(int id)
        {
            List<SelectListItem> adminValue = (from x in adm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.AdminRole,
                                                      Value = x.AdminID.ToString()
                                                  }).ToList();
            ViewBag.vlc = adminValue;
           

            var adminValue2 = adm.GetByID(id);
            return View(adminValue2);
        }

        [HttpPost]
        public ActionResult EditAdmin(Admin admin)
        {
            adm.AdminUpdate(admin);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteAdmin(int id) //aslinda guncelleme yapacak true-false
        {
            var adminvalue = adm.GetByID(id);
            if (adminvalue.AdminStatus == true)
            {
                adminvalue.AdminStatus = false;
            }
           
            adm.AdminDelete(adminvalue);
            return RedirectToAction("Index");
        }
    }
}

ExampleWebProject/Views/Authorization/AddAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "AddAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>

@using (Html.BeginForm("AddAdmin", "Authorization", FormMethod.Post))
{
<div class="form-group">
    <br />
    @Html.Label("Admin Kullanıcı Adı")
    @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })


    <br />

    @Html.Label("Şifreyi Giriniz")
    @Html.TextAreaFor(x => x.AdminPassword, new { @class = "form-control" })

    <br />

    @Html.Label("Rolü Seçiniz")
    @Html.TextAreaFor(x => x.AdminRole, new { @class = "form-control" })

    <br />
    <button id="btn1" class="btn btn-info">Kaydet</button>
    <script>
        $('#btn1').click(function () {
            swal("Eklendi!", "Başarılı bir şekilde eklendi!", "success");
        });
    </script>

</div>
}

ExampleWebProject/Views/Authorization/EditAdmin.cshtml
@model EntityLayer.Concrete.Admin
@{
    ViewBag.Title = "EditAdmin";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<script src="~/Scripts/jquery-3.4.1.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
@using (Html.BeginForm("EditAdmin", "Authorization", FormMethod.Post)) //metod,controller,ne yapinca calissin
{
<div class="form-group">
    <br />

    @Html.HiddenFor(x => x.AdminID, new { style = "display: none" })

    <br />
    @Html.Label("Admin Kullanıcı Adı")
    @Html.TextBoxFor(x => x.AdminUserName, new { @class = "form-control" })

    <br />
    @Html.HiddenFor(x => x.AdminPassword, new { @class = "form-control" })

    <br />
    @Html.Label("Rol")
    @Html.DropDownListFor(x => x.AdminID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })

    <br />
    <button id="btn1" class="btn btn-success">Güncelle</button>

</div>
    <script>
    $('#btn1').click(function () {
        swal("Güncellendi!", "Başarılı bir şekilde güncellendi!", "success");
    });
    </script>

}

ExampleWebProject/Views/Authorization/Index.cshtml
@using EntityLayer.Concrete
@model List<Admin>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{
    string status = "";
}

<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kullanıcı Mail</th>
        <th>Yetki</th>
        <th>Status</th>
        <th>Pasif Yap</th>
        <th>Yetkisini Değiştir</th>
    </tr>


    @foreach (var item in Model)
    {
        <tr>
            <th>@item.AdminID</th>
            <td>@item.AdminUserName</td>
            <td>@item.AdminRole</td>
            <td>
                @if (item.AdminStatus == true)
                {
                    status = "Aktif";
                }
                else if (item.AdminStatus == false)
                {
                    status = "Pasif";
                }
                @status
            </td>


            <td><a href="/Authorization/DeleteAdmin/@item.AdminID" class="btn btn-danger">Pasif Yap</a></td>
            <td><a href="/Authorization/EditAdmin/@item.AdminID" class="btn btn-warning">Yetkisini Değiştir</a></td>
        </tr>
    }
</table>
<a href="/Authorization/AddAdmin" class="btn btn-info">Yeni Admin Tanımla</a>