ExampleWebProject/Controllers/HeadingController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace ExampleWebProject.Controllers
{
    public class HeadingController : Controller
    {
        // GET: Heading
        HeadingManager hm = new HeadingManager(new EfHeadingDal());
        CategoryManager cm = new CategoryManager(new EfCategoryDal());
        WriterManager wm = new WriterManager(new EfWriterDal());
        public ActionResult Index()
        {
            var headingvalues = hm.GetList();
            return View(headingvalues);
        }
        public ActionResult GetListByCategoryId(int id)
        {
            var headingvalue = hm.GetListByCategoryId(id);
            return View(headingvalue);
        }
        public ActionResult HeadingReport()
        {
            var headingvalues = hm.GetList();
            return View(headingvalues);
        }

        [HttpGet]
        public ActionResult AddHeading()
        {
            List<SelectListItem> valuecategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();


            List<SelectListItem> valuewriter = (from x in wm.GetList()
                                                select new SelectListItem
                                                {
                                                    Text = x.WriterName + " " + x.WriterSurname,
                                                    Value = x.WriterID.ToString()
                                                }).ToList();

            ViewBag.vlw = valuewriter;
            ViewBag.vlc = valuecategory;
            return View();
        }

        [HttpPost]
        public ActionResult AddHeading(Heading p)
        {
            HeadingValidator categoryValidator = new HeadingValidator();
            ValidationResult results = categoryValidator.Validate(p);
            p.HeadingDate = DateTime.Parse(DateTime.Now.ToShortDateString());

            if (results.IsValid)
            {
                hm.HeadingAdd(p);
                
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return RedirectToAction("Index");

        }

        [HttpGet]
        public ActionResult EditHeading(int id)
        {
            List<SelectListItem> valuecategory = (from x in cm.GetList()
                                                  select new SelectListItem
                                                  {
                                                      Text = x.CategoryName,
                                                      Value = x.CategoryID.ToString()
                                                  }).ToList();
            ViewBag.vlc = valuecategory;

            var headingvalue = hm.GetByID(id);
            return View(headingvalue);
        }

        [HttpPost]
        public ActionResult EditHeading(Heading p)
        {
            hm.HeadingUpdate(p);
            return RedirectToAction("Index");
        }

        public ActionResult DeleteHeading(int id) //aslinda guncelleme yapacak true-false
        {
            var headingvalue = hm.GetByID(id);
            if(headingvalue.HeadingStatus == false)
            {
                headingvalue.HeadingStatus = true;
            }
            else if(headingvalue.HeadingStatus == true)
            {
                headingvalue.HeadingStatus = false;
            }
            hm.HeadingDelete(headingvalue);      
            return RedirectToAction("Index");
        }
     
    }
}

ExampleWebProject/Views/Heading/AddHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "AddHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h1>Yeni Başlık Ekleme</h1>

@using (Html.BeginForm("AddHeading", "Heading", FormMethod.Post))
{
<div class="form-group">
    @Html.Label("Başlık Adı")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.HeadingName)
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    <br />
    @Html.Label("Yazar")
    @Html.DropDownListFor(x => x.WriterID, (List<SelectListItem>)ViewBag.vlw, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.WriterID)
    <br />
    <button class="btn btn-info">Başlığı Oluştur</button>
</div>
}

ExampleWebProject/Views/Heading/EditHeading.cshtml
@model EntityLayer.Concrete.Heading
@{
    ViewBag.Title = "EditHeading";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<h2>Başlık Güncelleme Sayfası</h2>

@using(Html.BeginForm("EditHeading", "Heading" ,FormMethod.Post))
{ 
<div class="form-group">
    @Html.Label("Başlık ID")
    @Html.TextBoxFor(x => x.HeadingID, new { @class = "form-control" })
    <br />
    @Html.Label("Başlık Adı")
    @Html.TextBoxFor(x => x.HeadingName, new { @class = "form-control" })
    <br />
    @Html.Label("Tarih")
    @Html.TextBoxFor(x => x.HeadingDate, new { @class = "form-control" })
    <br />
    @Html.Label("YazarID")
    @Html.TextBoxFor(x => x.WriterID, new { @class = "form-control" })
    <br />
    @Html.Label("Kategori")
    @Html.DropDownListFor(x => x.CategoryID, (List<SelectListItem>)ViewBag.vlc, new { @class = "form-control" })
    <br />
    <button class="btn btn-success">Güncelle</button>
</div>
}

ExampleWebProject/Views/Heading/GetListByCategoryId.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "GetListByCategoryId";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@{ string color = "";
    string status = "";
}


<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <!-- Main Sidebar Container -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Yazar
                            </th>
                            <th style="width: 15%">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Seyahat")
                            {
                                color = "badge badge-warning";
                            }
                            else if (item.Category.CategoryName == "Spor")
                            {
                                color = "badge badge-success";
                            }
                            else if (item.Category.CategoryName == "Yazılım")
                            {
                                color = "badge badge-info";
                            }
                            else if (item.Category.CategoryName == "Kitap")
                            {
                                color = "badge badge-secondary";
                            }
                            else if (item.Category.CategoryName == "Kahve")
                            {
                                color = "badge badge-primary";
                            }
                            else if (item.Category.CategoryName == "Sanat")
                            {
                                color = "badge badge-success";
                            }


                            <tr>
                                <td>
                                    @item.HeadingID
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    @if (item.HeadingStatus == true)
                                    {
                                        status = "Aktif";
                                    }
                                    else if (item.HeadingStatus == false)
                                    {
                                        status = "Pasif";
                                    }
                                    @status
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        İçerik
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Heading/DeleteHeading/@item.HeadingID">
                                        @if (item.HeadingStatus == true)
                                        {
                                            status = "Pasif Et";
                                        }
                                        else if (item.HeadingStatus == false)
                                        {
                                            status = "Aktif Et";
                                        }
                                        <i class="fas fa-trash">
                                        </i>
                                        @status
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
    <a href="/Heading/AddHeading" class="btn btn-info">Yeni Başlık Girişi</a>
</body>
</html>

ExampleWebProject/Views/Heading/HeadingReport.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "HeadingReport";
    Layout = null;
}

<br />
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Raporlama Sayfası</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/css/bootstrap.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.5.2/css/buttons.bootstrap4.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/responsive/2.2.3/css/responsive.bootstrap4.min.css">
</head>
<body>
    <table id="example" class="table table-striped table-bordered dt-responsive nowrap" style="width:100%">
        <thead>
            <tr>
                <th>Başlık Id</th>
                <th>Başlık Adı</th>
                <th>Tarih</th>
                <th>Yazar</th>
                <th>Kategori</th>
                <th>Durum</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.HeadingID</td>
                    <td>@item.HeadingName</td>
                    <td>@item.HeadingDate</td>
                    <td>@item.Writer.WriterName @item.Writer.WriterSurname</td>
                    <td>@item.Category.CategoryName</td>
                    <td>@item.HeadingStatus</td>
                   
                </tr>
            }

        </tbody>
    </table>
    <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap4.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.bootstrap4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.print.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.2/js/buttons.colVis.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/dataTables.responsive.min.js"></script>
    <script src="https://cdn.datatables.net/responsive/2.2.3/js/responsive.bootstrap4.min.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('#example').DataTable({
                lengthChange: false,
                buttons: ['copy', 'excel', 'csv', 'pdf', 'colvis']
            });

            table.buttons().container()
                .appendTo('#example_wrapper .col-md-6:eq(0)');
        });
    </script>
</body>
</html>

ExampleWebProject/Views/Heading/Index.cshtml
@using EntityLayer.Concrete
@model List<Heading>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

@{ string color = "";
    string status = "";
}



<!DOCTYPE html>
<html>

<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <!-- Main Sidebar Container -->
    <!-- Content Wrapper. Contains page content -->
    <!-- Content Header (Page header) -->
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Başlık İşlemleri</h3>

                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                        <i class="fas fa-minus"></i>
                    </button>
                    <button type="button" class="btn btn-tool" data-card-widget="remove" data-toggle="tooltip" title="Remove">
                        <i class="fas fa-times"></i>
                    </button>
                </div>
            </div>
            <div class="card-body p-0">
                <table class="table table-striped projects">
                    <thead>
                        <tr>
                            <th style="width: 1%">
                                #
                            </th>
                            <th style="width: 20%">
                                Başlık Adı
                            </th>
                            <th style="width: 15%">
                                Yazar
                            </th>
                            <th style="width: 15%">
                                Durum
                            </th>
                            <th style="width: 8%" class="text-center">
                                Kategori
                            </th>
                            <th style="width: 20%">
                            </th>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var item in Model)
                        {
                            if (item.Category.CategoryName == "Seyahat")
                            {
                                color = "badge badge-warning";
                            }
                            else if (item.Category.CategoryName == "Spor")
                            {
                                color = "badge badge-success";
                            }
                            else if (item.Category.CategoryName == "Yazılım")
                            {
                                color = "badge badge-info";
                            }
                            else if (item.Category.CategoryName == "Kitap")
                            {
                                color = "badge badge-secondary";
                            }
                            else if (item.Category.CategoryName == "Kahve")
                            {
                                color = "badge badge-primary";
                            }
                            else if (item.Category.CategoryName == "Sanat")
                            {
                                color = "badge badge-success";
                            }


                            <tr>
                                <td>
                                    @item.HeadingID
                                </td>
                                <td>
                                    <a>
                                        @item.HeadingName
                                    </a>
                                    <br />
                                    <small>
                                        @(((DateTime)item.HeadingDate).ToString("dd-MMM-yyyy"))
                                    </small>
                                </td>
                                <td>
                                    <ul class="list-inline">
                                        <li class="list-inline-item">
                                            <img alt="Avatar" class="table-avatar" src="@item.Writer.WriterImage">
                                        </li>
                                    </ul>
                                </td>
                                <td>
                                    @if (item.HeadingStatus == true)
                                    {
                                        status = "Aktif";
                                    }
                                    else if (item.HeadingStatus == false)
                                    {
                                        status = "Pasif";
                                    }
                                    @status
                                </td>
                                <td class="project-state">
                                    <span class="@color">@item.Category.CategoryName</span>
                                </td>
                                <td class="project-actions text-right">
                                    <a class="btn btn-primary btn-sm" href="/Content/ContentByHeading/@item.HeadingID">
                                        <i class="fas fa-folder">
                                        </i>
                                        İçerik
                                    </a>
                                    <a class="btn btn-info btn-sm" href="/Heading/EditHeading/@item.HeadingID">
                                        <i class="fas fa-pencil-alt">
                                        </i>
                                        Düzenle
                                    </a>
                                    <a class="btn btn-danger btn-sm" href="/Heading/DeleteHeading/@item.HeadingID">
                                        @if (item.HeadingStatus == true)
                                        {
                                            status = "Pasif Et";
                                        }
                                        else if (item.HeadingStatus == false)
                                        {
                                            status = "Aktif Et";
                                        }
                                        <i class="fas fa-trash">
                                        </i>
                                        @status
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
        <!-- /.card -->

    </section>
    <!-- /.content -->
    <a href="/Heading/AddHeading" class="btn btn-info">Yeni Başlık Girişi</a>
</body>
</html>